---
# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    chan_trai_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    chan_phai_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    joints:
       - joint_1
       - joint_2
       - joint_3
       - joint_4
    state_interfaces:
       - position

chan_trai_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

chan_phai_controller:
  ros__parameters:
    joints:
      - joint_3
      - joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity