# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    chan_phai_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    chan_trai_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

chan_phai_controller:
  ros__parameters:
    joints:
      - joint_3
      - joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
chan_trai_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity