---
controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    chan_trai_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint_1
        - joint_2
    chan_phai_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint_3
        - joint_4
        